import { MenuItem } from '@/contracts/menu-item-contract'

export const ADMIN_MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    label: 'storage',
    desc: 'storage_desc',
    route: './storage',
    svg: 'STORAGE',
    color: 'primary',
    permissions: ['STORAGE_GET_ALL_CONTAINERS'],
  },
  {
    id: 2,
    label: 'legal_document_management',
    desc: 'legal_document_desc',
    route: './rera-legal-storage',
    svg: 'LEGAL',
    color: 'primary-outline',
    permissions: ['ADMIN_GET_LEGAL_CONTAINER'],
  },
  {
    id: 3,
    label: 'indexers',
    desc: 'indexers_desc',
    route: './indexer',
    svg: 'INDEXER',
    color: 'accent',
    permissions: ['INDEXES_NAMES'],
  },
  {
    id: 4,
    label: 'users',
    desc: 'users_desc',
    route: './users',
    svg: 'USERS',
    color: 'accent-outline',
    permissions: ['ADMIN_GET_ALL_USER'],
  },
  {
    id: 5,
    label: 'web_crawler',
    desc: 'web_crawling_desc',
    route: './crawler',
    svg: 'WEB_CRAWLER',
    color: 'secondary',
    permissions: ['MEDIA_CRAWL'],
  },
  {
    id: 6,
    label: 'faq_manager',
    desc: 'faq_manager_desc',
    route: './faq',
    svg: 'FAQ',
    color: 'secondary-outline',
    permissions: ['FAQ_GET_ALL_QUESTIONS'],
  },
  {
    id: 7,
    label: 'social_media_crawling',
    desc: 'social_media_crawling_desc',
    route: './social-media',
    svg: 'MEDIA_CRAWLER',
    color: 'tertiary',
    permissions: ['SOCIAL_MEDIA'],
  },
]
