export interface LangKeysContract {
  open_avatar: string
  send: string
  search_message: string
  preview: string
  is_background_video: string
  background_color: string
  background_url: string
  logo_url: string
  try_it_out: string
  document_search_description: string
  chat_description: string
  local_key: string
  arabic_local: string
  english_local: string
  localization: string
  save: string
  cancel_recording: string
  clear_chat_history: string
  stop_talking: string
  settings: string
  click_to_speak: string
  loading: string
  listening_ongoing: string
  click_to_send: string
  connected: string
  not_connected: string
  connecting: string
  disconnecting: string
  home: string
  search: string
  chat: string
  avatar_chat: string
  welcome_message: string
  generic: string
  video_indexer: string
  custom: string
  show_more: string
  show_less: string
  result_count: string
  search_about: string
  search_in_website: string
  items_per_page_label: string
  next_page_label: string
  previous_page_label: string
  first_page_label: string
  last_page_label: string
  page: string
  of: string
  video_token: string
  chat_history: string
  select_filter: string
  bot_name: string
  feedback: string
  sentiment: string
  dislike: string
  like: string
  negative: string
  mixed: string
  positive: string
  neutral: string
  feedback_chart: string
  sentiment_chart: string
  performance_chart: string
  no_data_to_preview: string
  rate_conversation: string
  i_like: string
  i_dislike: string
  conversations_and_chats: string
  choose_conversation: string
  conversation_description: string
  unspecified: string
  all_bots: string
  choose_bot: string
  conversation_title: string
  sentiment_analysis_description: string
  reload_conversation: string
  sort_conversation: string
  total: string
  doc_analyzer: string
  not_supported_filetype: string
  exceed_file_size: string
  upload: string
  remove: string
  click_to_upload_or_dnd: string
  file_upload: string
  next: string
  previous: string
  extracted_data: string
  extracted_words: string
  document_analyze_progress: string
  vacation_request: string
  interactive_chatbot: string
  vacations_list: string
  employee_name: string
  manager_name: string
  department: string
  start_date: string
  end_date: string
  total_days: string
  status: string
  comments: string
  actions: string
  approved: string
  rejected: string
  pending: string
  vacation_type: string
  web_crawler_and_report_generator: string
  generate_report: string
  topics: string
  web_page_urls: string
  crawl_web_pages: string
  search_text_for_report: string
  invalid_url: string
  required: string
  web_crawler: string
  change_bot: string
  change_bot_note: string
}
