export interface LangKeysContract {
  try_it_out: string
  document_search_description: string
  chat_description: string
  local_key: string
  arabic_local: string
  english_local: string
  localization: string
  save: string
  cancel_recording: string
  clear_chat_history: string
  stop_talking: string
  settings: string
  click_to_speak: string
  loading: string
  listening_ongoing: string
  click_to_send: string
  connected: string
  not_connected: string
  connecting: string
  disconnecting: string
  home: string
  search: string
  chat: string
  avatar_chat: string
  welcome_message: string
  generic: string
  video_indexer: string
  custom: string
}
